import { v4 as uuid4 } from "uuid";

// const bakery = [
//   {
//     "teacakes": [
//                 {
//                 name: "teacake 1",
//                 price: 2.0,
//                 description: "Freshly baked bread",
//                 image: "/assets/img/menu/spinach-salad.jpg",
//                 category: "teacakes",
//                 id: 1,
//                 },
//                 {
//                 name: "teacake 2",
//                 price: 1.0,
//                 description: "Freshly baked bagel",
//                 image: "/assets/img/menu/spinach-salad.jpg",
//                 category: "teacakes",
//                 id: 2,
//                 },
//                 {
//                 name: "teacake 3",
//                 price: 1.5,
//                 description: "Freshly baked croissant",
//                 image: "/assets/img/menu/spinach-salad.jpg",
//                 category: "teacakes",
//                 id: 3,
//                 },
//             ]
//         }
//   ,{
//     "pastry": [
//                 {
//                 name: "pastry 1",
//                 price: 2.0,
//                 description: "Freshly baked bread",
//                 image: "/assets/img/menu/spinach-salad.jpg",
//                 category: "pastry",
//                 id: 4,
//                 },
//                 {
//                 name: "pastry 2",
//                 price: 1.0,
//                 description: "Freshly baked bagel",
//                 image: "/assets/img/menu/spinach-salad.jpg",
//                 category: "pastry",
//                 id: 5,
//                 },
//             ]
//     }
// ];

const bakery = [
  {
    name: "Tea Cakes",
    uuid: uuid4(),
    data: [
      {
        name: "Chocolate Tea Cake",
        price: 279,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/bakery/TeaCakes/Chocolate.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Choco Walnut Tea Cake",
        price: 319,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/TeaCakes/ChocoWalnut.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Vanilla Tea Cake",
        price: 249,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/TeaCakes/Vanilla.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Marble Tea Cake",
        price: 269,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/bakery/TeaCakes/Marble.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Choco Chip Tea Cake",
        price: 279,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/TeaCakes/ChocoChip.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Choco Almond Tea Cake",
        price: 319,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/TeaCakes/chocolateAlmond.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Dry Fruit Tea Cake",
        price: 319,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/TeaCakes/DryFruit.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Berrylicious Tea Cake",
        price: 319,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/bakery/TeaCakes/Berrylicious.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Banana Walnut Tea Cake",
        price: 319,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/bakery/TeaCakes/BananaWalnut.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Pastry",
    uuid: uuid4(),
    data: [
      {
        name: "Pineapple Cream Cheese",
        price: 219,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Pastry/Pineapple.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Access",
        price: 269,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/ChocolateAccess.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Pastry",
        price: 545,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/ChocolatePastery.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Truffle",
        price: 269,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Pastry/chocolatetruffle.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Red Velvet",
        price: 550,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/redVelvet.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "Chocolate Black Forest",
      //   price: 189,
      //   // description: "Rich and aromatic caffeine shot",
      //   image: "/assets/img/menu/bakery/Pastry/chocolateBlackForest.jpeg",
      //   uuid: uuid4(),
      // },
      {
        name: "BlueBerry Cheese Cake",
        price: 249,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/blueBerryCheeseCake.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Biscoff Cheese Cake",
        price: 550,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/BiscoffCheesepastry.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Balck Forest",
        price: 189,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Pastry/chocolateBlackForest.jpeg",
        uuid: uuid4(),
      },
      {
        name: "BlueBerry Cheese Cake",
        price: 279,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/blueBerryCheeseCake.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Tiramisu Pastry",
        price: 269,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/tiramisu.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Red Velvet Jar",
        price: 279,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/redVelvetJar.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Tiramisu Jar",
        price: 249,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/TiramisuJar.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Tart",
        price: 199,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Pastry/chocolateTart.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Brownie And Muffins",
    uuid: uuid4(),
    data: [
      {
        name: "Walnut Brownie",
        price: 249,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/WalnutBrownie.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Brownie with Ice Cream",
        price: 269,
        // description: "Espresso with milk foam",
        image:
          "/assets/img/menu/bakery/BrownieAndMuffins/BrownieWithIceCream.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Vanilla Muffin",
        price: 109,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/VanillaMuffin.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Blueberry Muffin",
        price: 119,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/BlueberryMuffin.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Muffin",
        price: 129,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/ChocolateMuffin.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Choco Chip Muffin",
        price: 129,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/ChocoChipMuffin.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Apple Pie",
        price: 199,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/applePie.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Walnut Brownie",
        price: 249,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/BrownieAndMuffins/ChocolateWalnutBrownie.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Cookies",
    uuid: uuid4(),
    data: [
      {
        name: "Choco Chip  Cookies (200 gm)",
        price: 219,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/cookies/ChocoChip.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Oats & Raisins Cookies (200 gm)",
        price: 285,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/cookies/OatsAndRaisins.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Small Cookie (1 pc)",
        price: 45,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/cookies/ChocoChip.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Almond Biscotti  Cookies (200 gm)",
        price: 290,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/cookies/almondbiscotti.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Coffee Cookie (1 pc)",
        price: 45,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/cookies/CoffeeCookie.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Fudge Cookies (200 gm)",
        price: 219,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/cookies/ChocolateFudgeCookie.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Atta Cookies (200 gm)",
        price: 199,
        // description: "(200 gm)",
        image: "/assets/img/menu/bakery/cookies/attaCookies.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Breads",
    uuid: uuid4(),
    data: [
      {
        name: "Brown Bread",
        price: 45,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Breads/brownBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Sandwich Bread",
        price: 40,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/SandwichBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Multigrain Bread",
        price: 60,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Breads/MultigrainBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Focaacia Bread",
        price: 45,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/FocacciaBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Multigrain Loaf",
        price: 45,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Breads/MultigrainLoaf.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Burger Bun",
        price: 20,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/burgerBun.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Multigrain Bun",
        price: 60,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Breads/MultigrainBun.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Pita Bread",
        price: 35,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/pitaBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Pao",
        price: 35,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/bakery/Breads/paw.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Pizza Base",
        price: 35,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/PizzaBase.webp",
        uuid: uuid4(),
      },
      {
        name: "Pizza Base Brown",
        price: 30,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/bakery/Breads/PizzaBaseBrown.jpeg",
        uuid: uuid4(),
      },
    ],
  },
];
const beverages = [
  {
    name: "Espressos",
    uuid: uuid4(),
    data: [
      {
        name: "Espresso",
        price: 169,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/Espressos/Espresso.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Maachiato",
        price: 189,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/Espressos/Maachiato.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Americano",
        price: 199,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/beverages/Espressos/Americano.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cafe Medici",
        price: 219,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/beverages/Espressos/Cafe Medici.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Classic Coffee",
    uuid: uuid4(),
    data: [
      {
        name: "Latte",
        price: 245,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/classicCoffee/latte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cappuccino",
        price: 255,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/classicCoffee/cappuccino.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Spanish Latte(blend)",
        price: 255,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/beverages/classicCoffee/SpanishLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Organic Macha Latte(Hot/Iced)",
        price: 255,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/beverages/classicCoffee/OrganicMachaLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Flat White",
        price: 285,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/classicCoffee/FlatWhite.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cafe Mocha",
        price: 295,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/classicCoffee/CafeMocha.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Iced Coffee",
    uuid: uuid4(),
    data: [
      {
        name: "Iced Americano",
        price: 215,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/IcedCoffee/IcedAmericano.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Latte",
        price: 235,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/IcedCoffee/IcedLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Cappuccino",
        price: 275,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/beverages/IcedCoffee/IcedCappuccino.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cold Coffee",
        price: 289,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/beverages/IcedCoffee/ColdCoffee.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Vietnamese Cold Coffee",
        price: 319,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/IcedCoffee/VietnameseColdCoffee.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Chocolate Drinks",
    uuid: uuid4(),
    data: [
      {
        name: "Hot Chocolate",
        price: 299,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/ChocolateDrinks/HotChocolate.jpg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Latte",
        price: 319,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/ChocolateDrinks/ChocolateLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Choclate Venoice",
        price: 319,
        // description: "Espresso shot mixed with ice",
        image:
          "/assets/img/menu/beverages/ChocolateDrinks/chocolateVenoice.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Chocolate",
        price: 329,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/beverages/ChocolateDrinks/IcedChocolate.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Tea",
    uuid: uuid4(),
    data: [
      {
        name: "Decaf",
        price: 55,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/Tea/Decaf.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Classic",
        price: 235,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/Tea/classic.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Premium",
        price: 255,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/Tea/Premium.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Shakes",
    uuid: uuid4(),
    data: [
      {
        name: "Strawberry Shake",
        price: 319,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/shakes/Strawberry.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Blueberry Shake",
        price: 319,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/shakes/Blueberry.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Oreo Shake",
        price: 329,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/beverages/shakes/Oreo.jpeg",
        uuid: uuid4(),
      },
      {
        name: "KitKat Shake",
        price: 329,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/beverages/shakes/kitkat.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Mocha Shake",
        price: 339,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/shakes/Mocha.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Banoffee Shake",
        price: 369,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/shakes/Banoffee.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Mocktails",
    uuid: uuid4(),
    data: [
      {
        name: "Ice Tea",
        price: 169,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/beverages/mocktails/IceTea.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Lemon Tea",
        price: 169,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/beverages/mocktails/LeamonTea.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Virgin Mojito",
        price: 249,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/beverages/mocktails/VirginMojito.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Lime Soda",
        price: 249,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/beverages/mocktails/LimeSoda.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Smoothies",
    uuid: uuid4(),
    data: [
      {
        name: "Banana Smoothie",
        price: 325,
        // description: "Freshly made from milk and banana",
        image: "/assets/img/menu/beverages/smoothies/banana-smoothie.jpg",
        uuid: uuid4(),
      },
      {
        name: "Blueberry Smoothie",
        price: 335,
        // description: "Freshly made from milk and blueberry",
        image: "/assets/img/menu/beverages/smoothies/blueberry-smoothie.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Mixed Berry Smoothie",
        price: 335,
        // description: "Freshly made from milk and blueberry",
        image: "/assets/img/menu/beverages/smoothies/Mixed Berry.jpeg",
        uuid: uuid4(),
      },
    ],
  },
];
const food = [
  {
    name: "Breakfast Classics",
    uuid: uuid4(),
    data: [
      {
        name: "Plain Croissant",
        price: 109,
        description: "Serving Size 60g Calories 226 Allergens: milk, gluten, eggs",
        image: "/assets/img/menu/food/breakfast/plaincroissant.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Croissant",
        price: 149,
        description: "Serving Size 60g Calories 226 Allergens: milk, gluten, eggs",
        image: "/assets/img/menu/food/breakfast/chocolatecroissant.jpg",
        uuid: uuid4(),
      },
      {
        name: "Stuffed Croissant",
        price: 149,
        description: "Serving Size 60g Calories 226 Allergens: milk, gluten, eggs",
        image: "/assets/img/menu/food/breakfast/stuffedcroissant.jpeg",
        uuid: uuid4(),
      },
      {
        name: "French Butter & Croissant",
        price: 175,
        description: "Serving Size 60g Calories 226 Allergens: milk, gluten, eggs",
        image: "/assets/img/menu/food/breakfast/FrenchCroissant.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cheese Omelette",
        price: 325,
        description: "Serving Size 200g Calories 373 Allergens: milk, eggs Add On: Chicken: 125",
        image: "/assets/img/menu/food/breakfast/CheeseOmelette.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Scrambled Eggs & Broma Multigrain Flemish Toast",
        price: 415,
        description: "Serving Size 250g Calories 527 Allergens:milk, gluten, eggs, soybean, sesame",
        image: "/assets/img/menu/food/breakfast/ScrambledEggsToast.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Coffee & Croissant",
        price: 425,
        description: "Please select a coffee of your choice from our coffee menu Calories 367 Allergens: milk,gluten, eggs",
        image: "/assets/img/menu/food/breakfast/CoffeeAndCroissant.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "Belgium Waffles",
      //   price: 295,
        // description: "Espresso with milk foam",
      //   image: "/assets/img/menu/food/breakfast/BelgiumWaffles.jpeg",
      //   uuid: uuid4(),
      // },
      // {
      //   name: "Blueberry Waffles",
      //   price: 295,
        // description: "Espresso shot mixed with ice",
      //   image: "/assets/img/menu/food/breakfast/BlueberryWaffles.jpeg",
      //   uuid: uuid4(),
      // },
      // {
      //   name: "Nutella Banana Waffle",
      //   price: 315,
      //   description: "Espresso with chocolate and milk foam",
      //   image: "/assets/img/menu/food/breakfast/NutellaBananaWaffle.jpeg",
      //   uuid: uuid4(),
      // },
      {
        name: "Broma Waffle",
        price: 325,
        description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/food/breakfast/BromaWaffle.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Broma Pancake",
        price: 345,
        description: "Espresso with milk foam",
        image: "/assets/img/menu/food/breakfast/BromaPancake.jpeg",
        uuid: uuid4(),
      },
      
      {
        name: "Green Shakshuka Baked Eggs",
        price: 395,
        description: "Baked organic eggs with garlic, spinach, kale, Broma Basil Pesto",
        image: "/assets/img/menu/food/breakfast/GreenShakshukaBakedEggs.jpeg",
        uuid: uuid4(),
      },
      {
        name: "White Omelette with chia, Spinach&Parmesan",
        price: 495,
        description: "Serving Size 200g Calories 367 Allergens: milk, eggs",
        image: "/assets/img/menu/food/breakfast/WhiteOmelettewithchiaSpinachParmesan.jpeg",
        uuid: uuid4(),
      },
      {
        name: "The English in India",
        price: 585,
        description: "Eggs your style with the choice of chicken sausages,Abmika’s spiced baked beans, button mushrooms, roasted tomato, crushed potatoes",
        image: "/assets/img/menu/food/breakfast/EnglishInIndia.jpeg",
        uuid: uuid4(),
      },
    ],    
  },
  {
    name: "Salads",
    uuid: uuid4(),
    data: [
      {
        name: "Green Goddess Buddha Bowl",
        price: 425,
        description: "Quinoa, Spinach and Parsley Hummus, tofu, rocket, snowpeas, broccoli, gluten free five seed crackers, Broma Basil Pesto",
        image: "/assets/img/menu/food/salads/GreenGoddessBuddhaBowl.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "Caesar Salad",
      //   price: 495,
        // description: "Serving Size 250g Calories 458 Allergens: milk, soybean, sulphite, gluten",
      //   image: "/assets/img/menu/food/salads/TuscanKaleAvocadoCaesarSalad.jpeg",
      //   uuid: uuid4(),
      // },
      {
        name: "Caesar Salad",
        price: 575,
        description: "Serving Size 280g Calories 607 Allergens: milk, gluten, eggs, soybean, sulphite",
        image: "/assets/img/menu/food/salads/ChickenAvocadoCaesarSalad.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Full Power Grain Superfood Salad",
        price: 685,
        description: "Quinoa, barley, avocado and broccoli Serving Size 280g Calories 462 Allergens: milk,soybean, sulphite, gluten, tree nuts For some extra protein, add on grilled chicken 150/-",
        image: "/assets/img/menu/food/salads/FullPowerGrainSuperfoodSalad.jpeg",
        uuid: uuid4(),
      },
    ],
  }
  ,
  {
    name: "Add To Your Salad",
    uuid: uuid4(),
    data: [
      {
        name: "Silken Tofu",
        price: 95,
        description: "Serving size 70g Calories 44",
        image: "/assets/img/menu/food/addToYourSalad/SilkenTofu.jpeg",
        uuid: uuid4(),
      },
     
      {
        name: "Grilled Chicken",
        price: 150,
        description: "Serving size 70g Calories 158",
        image: "/assets/img/menu/food/addToYourSalad/GrilledChicken.jpeg",
        uuid: uuid4(),
      },
    ],
  }
  ,{
    name: "Pizza",
    uuid: uuid4(),
    data: [
      {
        name: "Margherita",
        price: 465,
        description: "Serving Size 320g Calories 498 Allergens: soybean, gluten",
        image: "/assets/img/menu/food/pizza/Margherita.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "Legume Ala Pizza",
      //   price: 485,
      //   description: "Exctic veg. pizza with fresh baked cheese and sundried tomatoes",
      //   image: "/assets/img/menu/food/pizza/LegumeAlaPizza.jpeg",
      //   uuid: uuid4(),
      // },
      {
        name: "Alfredo Spinach & Corn",
        price: 495,
        description: "Sun dried tomato, mushroom sauce, spinach, corn and red peprika",
        image: "/assets/img/menu/food/pizza/AlfredoSpinachCorn.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "The Kernel Delight",
      //   price: 495,
      //   description: "Corn kernel with cheese and fresh basil",
      //   image: "/assets/img/menu/food/pizza/TheKernelDelight.jpeg",
      //   uuid: uuid4(),
      // },
      {
        name: "Basil Pesto with Toasted Pine Nuts",
        price: 525,
        description: "Serving Size 320g Calories 835 Allergens: milk, soybean, gluten, tree nuts",
        image: "/assets/img/menu/food/pizza/BurrataBasilPestowithToastedPineNuts.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Smoked Chicken Feta",
        price: 535,
        description: "Mozzarella, culted spinach, corn, red peprika and feta",
        image: "/assets/img/menu/food/pizza/SmokedChickenFeta.jpeg",
        uuid: uuid4(),
      },      
      {
        name: "Polo Ala Pizzare",
        price: 545,
        description: "Grilled chicken with onion, vegetables and cheese",
        image: "/assets/img/menu/food/pizza/PoloAlaPizzare.jpeg",
        uuid: uuid4(),
      },
      // {
      //   name: "Broma Pepperoni",
      //   price: 595,
      //   description: "Serving Size 320g Calories 772 Allergens: milk, soybean, gluten",
      //   image: "/assets/img/menu/food/pizza/BromaPepperoni.jpeg",
      //   uuid: uuid4(),
      // },
    
    ], 
  },
  {
    name: "Add To Your Pizza",
    uuid: uuid4(),
    data: [
 
      {
        name: "FarmLove Vegetables",
        price: 125,
        description: "Serving size 50g Calories 39",
        image: "/assets/img/menu/food/addToYourPizza/FarmLoveVegetables.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Grilled Parsley Mushrooms",
        price: 125,
        description: "Serving size 23g Calories 122",
        image: "/assets/img/menu/food/addToYourPizza/GrilledParsleyMushrooms.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Marinated Chicken",
        price: 150,
        description: "Serving size 70g Calories 58",
        image: "/assets/img/menu/food/addToYourPizza/MarinatedChicken.jpeg",
        uuid: uuid4(),
      },
    ],
  }
  ,{
    name: "Pasta",
    uuid: uuid4(),
    data: [
      {
        name: "Broma Aglio E Olio Spaghetti",
        price: 415,
        description: "Serving Size 250g Calories 440 Allergens: milk, soybean, gluten",
        image: "/assets/img/menu/food/pasta/BromaAglioEOlioSpaghetti.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Penne All Arrabbiata",
        price: 525,
        description: "Serving Size 322g Calories 486 Allergens: milk, soybean, gluten",
        image: "/assets/img/menu/food/pasta/OrecchietteAllArrabbiata.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Alfredo Pasta",
        price: 525,
        description: "Serving Size 322g Calories 486 Allergens: milk, soybean, gluten",
        image: "/assets/img/menu/food/pasta/alfredoPasta.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Green Shakashuka Pasta",
        price: 535,
        description: "Serving Size 300g Calories 756 Allergens: milk, gluten",
        image: "/assets/img/menu/food/pasta/FettuccineWithButtonMushroomTruffleRagu.jpeg",
        uuid: uuid4(),
      },
    ]
  },
  {
    name: "Add To Your Pasta",
    uuid: uuid4(),
    data: [
      {
        name: "Add a seasonal vegetable to your pasta",
        price: 49,
        description: "Serving size 50g Calories 39",
        image: "/assets/img/menu/food/addToYourPasta/FarmLoveVegetables.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Add Chicken to your pasta",
        price: 79,
        description: "Serving size 50g Calories 46",
        image: "/assets/img/menu/food/addToYourPasta/chicken.jpeg",
        uuid: uuid4(),
      },
 
    ],
  },
  {
    name: "Large Plates",
    uuid: uuid4(),
    data: [
      {
        name: "Falafel & Hummus Sandwich",
        price: 325,
        description: "Crispy Falafel, hummus and pickles with spice sauce",
        image: "/assets/img/menu/food/largePlates/FalafelHummusSandwich.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Ham & Cheese Sandwich",
        price: 365,
        description: "Cooked chicken and cheese in mozzarella",
        image: "/assets/img/menu/food/largePlates/HamCheeseSandwich.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Grilled Veggie Sandwich",
        price: 375,
        description: "Grilled veggie mushroom, bellpeppers, bull pepprin multigrain bread",
        image: "/assets/img/menu/food/largePlates/GrilledVeggieSandwich.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Grilled Chicken Sandwich",
        price: 395,
        description: "Espresso with milk foam",
        image: "/assets/img/menu/food/largePlates/GrilledChickenSandwich.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Green Goddess Sandwich in Broma Multigrain Bread",
        price: 575,
        description: "Broma basil pesto, spinach and parsley hummus, grain mustard aioli, avocado and FarmLove greens. Served with herb, spiced truffle fries",
        image: "/assets/img/menu/food/largePlates/GreenGoddessSandwichBromaMultigrainBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Sub",
        price: 399,
        description: "Crispy bacon, chicken breast, FarmLove mixed greens, grain mustard aioli and cheese emmental. ",
        image: "/assets/img/menu/food/largePlates/BromaTripleDeckerMultigrainClubSandwich.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Grilled Chicken Breast (gf)",
        price: 595,
        description: "Served with potato puree, buttered FarmLove veggies and bourbon pepper cream sauce",
        image: "/assets/img/menu/food/largePlates/GrilledChickenBreast.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Sides",
    uuid: uuid4(),
    data: [
      {
        name: "Multigrain Flemish Toast",
        price: 75,
        description: "Serving Size 50g Calories 174 Allergens: milk, gluten, soybean",
        image: "/assets/img/menu/food/sides/MultigrainFlemishToast.jpeg",
        uuid: uuid4(),
      },
      {
        name: " Crushed Potatoes",
        price: 125,
        description: "Serving Size 100g Calories 148 Allergens: milk",
        image: "/assets/img/menu/food/sides/CrushedPotatoes.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Sauteed Assorted Mushrooms",
        price: 155,
        description: "Serving Size 120g Calories 142Allergens: milk",
        image: "/assets/img/menu/food/sides/AssortedMushrooms.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chicken Sauasages (2 slices)",
        price: 165,
        description: "Serving Size 150g Calories 330 Allergens: gluten, soybean",
        image: "/assets/img/menu/food/sides/Sausages.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Classic Salted Potato Fries",
        price: 165,
        description: "Serving Size 120g Calories 276 Allergens: soybean",
        image: "/assets/img/menu/food/sides/PotatoFries.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cheese Garlic Breads",
        price: 195,
        description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/food/sides/GarlicBread.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Potato Wedge's",
        price: 195,
        description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/food/sides/PotatoWedges.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Broma Spice, Herb & Parmesan Fries",
        price: 215,
        description: "Serving Size 120g Calories 258 Allergens: soybean",
        image: "/assets/img/menu/food/sides/ParmesanFries.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Sauteed Buttered Vegetables",
        price: 299,
        description: "Serving Size 150g Calories 149 Allergens: milk",
        image: "/assets/img/menu/food/sides/SauteedButteredVegetables.jpeg",
        uuid: uuid4(),
      }
    ],
    
  },
  {
    name: "Burger",
    uuid: uuid4(),
    data: [
      {
        name: "Broma Veg Burger",
        price: 379,
        description: "Bun stuffed with veg. patties and cheese, jalapenos,caramilised onions and lettuce",
        image: "/assets/img/menu/food/burger/VegBurger.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Broma Non-Veg Burger",
        price: 429,
        description: "Bun stuffed with chicken patties and caramilised onions, lettuce and tomato",
        image: "/assets/img/menu/food/burger/NonVegBurger.jpeg",
        uuid: uuid4(),
      },
    ],
  },
];
const onWheels = [
  {
    name: "Hot Beverages",
    uuid: uuid4(),
    data: [
      {
        name: "Tea",
        price: 45,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/onWheels/HotBeverages/classic.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Americano",
        price: 49,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/onWheels/HotBeverages/Americano.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Espresso",
        price: 55,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/HotBeverages/Espresso.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Flat White",
        price: 69,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/onWheels/HotBeverages/FlatWhite.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cappuccino",
        price: 85,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/HotBeverages/cappuccino.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cafe Latte",
        price: 85,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/onWheels/HotBeverages/latte.jpeg",
        uuid: uuid4(),
      },    
      {
        name: "Cafe Mocha",
        price: 109,
        // description: "Espresso with milk foam",
        image: "/assets/img/menu/onWheels/HotBeverages/CafeMocha.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Spanish Latte",
        price: 119,
        // description: "Espresso shot mixed with ice",
        image: "/assets/img/menu/onWheels/HotBeverages/SpanishLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Hot Chocolate",
        price: 139,
        // description: "Espresso with chocolate and milk foam",
        image: "/assets/img/menu/onWheels/HotBeverages/HotChocolate.jpg",
        uuid: uuid4(),
      },
     
    ],
  },

  {
    name: "Cold Beverages",
    uuid: uuid4(),
    data: [
      {
        name: "Iced Tea",
        price: 59,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/IceTea.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Fresh Lime Soda",
        price: 69,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/LimeSoda.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Lemon Iced Tea",
        price: 79,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/LeamonTea.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Chocolate Shake",
        price: 100,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/Mocha.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Americano",
        price: 109,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/IcedLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Cappucino",
        price: 119,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/IcedCappuccino.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Iced Latte",
        price: 120,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/onWheels/ColdBeverages/IcedLatte.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Strawbery Shake",
        price: 120,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/Strawberry.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Oreo Shake",
        price: 120,
        // description: "Espresso with milk foam",
        image:
          "/assets/img/menu/onWheels/ColdBeverages/Oreo.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Kit-Kat Shake",
        price: 120,
        // description: "Classic Latte without caffeine",
        image: "/assets/img/menu/onWheels/ColdBeverages/kitkat.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cold Coffee",
        price: 140,
        // description: "Espresso with milk foam",
        image:
          "/assets/img/menu/onWheels/ColdBeverages/ColdCoffee.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Mocha Shake",
        price: 149,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/onWheels/ColdBeverages/Mocha.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Cold Chocolate",
        price: 159,
        // description: "Espresso mixed with condensed milk",
        image: "/assets/img/menu/onWheels/ColdBeverages/IcedChocolate.jpeg",
        uuid: uuid4(),
      },
    
     
      {
        name: "Vietnamese Cold Coffee",
        price: 159,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/ColdBeverages/VietnameseColdCoffee.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Flavors",
    uuid: uuid4(),
    data: [
      {
        name: "Hazelnut",
        price: 35,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/flavours/hazelnut.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Irish",
        price: 35,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/flavours/hazelnut.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Caramel",
        price: 35,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/flavours/caramel.jpeg",
        uuid: uuid4(),
      },
      {
        name: "Vanilla",
        price: 35,
        // description: "Rich and aromatic caffeine shot",
        image: "/assets/img/menu/onWheels/flavours/vanilla.jpeg",
        uuid: uuid4(),
      },
    ],
  },
  {
    name: "Food",
    uuid: uuid4(),
    data: [
      {
        name: 'Maggi',
        price: 39,
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/maggie.jpeg',
        uuid: 'e0e3073c-9bf2-45f1-a470-6f2b883d2f35'
      },
      {
        name: 'Boiled Eggs (3)',
        price: 49,
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/boiledEggs.jpeg',
        uuid: '99e3949e-0c5f-4e01-8c9c-37a824aa9482'
      },
      {
        name: 'Veg Burger',
        price: 60,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/VegBurger.jpeg',
        uuid: 'b15c945f-48e5-4d4a-8ae1-d06fffa0f9de'
      },
      {
        name: 'Masala Maggi',
        price: 59,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/MasalaMaggie.jpeg',
        uuid: '036f3cd6-02db-4a0c-ba86-761d832b731b'
      },
      {
        name: 'Egg Maggi',
        price: 69,
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/EggMaggi.jpeg',
        uuid: '515e8647-5f1d-4f32-8a07-c7a9cc31f0b2'
      },
      {
        name: 'Veg Sandwich',
        price: 99,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/GrilledVeggieSandwich.jpeg',
        uuid: '3617c8c6-8d69-4b0b-8366-88b8e6a5f7c4'
      },
      {
        name: 'Non-Veg Sandwich',
        price: 109,
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/GrilledChickenSandwich.jpeg',
        uuid: '75089f07-82ea-41e0-bb5f-3e416baa6c11'
      },
      {
        name: 'Pizza (Veg/Non-Veg)',
        price: '109/139',
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/LegumeAlaPizza.jpeg',
        uuid: '5458b4f7-67c6-48f1-90a2-3720135b97a2'
      },
      {
        name: 'Non-Veg Burger',
        price: 89,
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/NonVegBurger.jpeg',
        uuid: 'a33dd65b-05f3-49e7-91e7-351cd348660d'
      },
      {
        name: 'Omelette',
        price: 89,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/CheeseOmelette.jpeg',
        uuid: '93e3da18-2aa2-49e0-8e5e-ae0d0d92cfd0'
      },
      {
        name: 'Pasta (veg/non-veg)',
        price: '129/149',
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/pasta.jpeg',
        uuid: 'd9ea867d-26f6-45e5-b74e-44b04d9c3a7b'
      },
      {
        name: 'Penne: White Sauce/Red Sauce',
        price: '139/159',
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/pasta.jpeg',
        uuid: 'ef2e9a67-057d-4a05-bc9d-6a48f61f1c02'
      },
      {
        name: 'Spaghetti: Aglio e Olio',
        price: '119/139',
        description: 'Espresso with milk foam',
        image: '/assets/img/menu/onWheels/Snacks/BromaAglioEOlioSpaghetti.jpeg',
        uuid: 'f2b3fc0c-b0d5-4ad3-8693-7d4d798b5979'
      },
      {
        name: 'Garlic Bread (3)',
        price: 139,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/GarlicBread.jpeg',
        uuid: '2e94b59d-ee2e-4b02-9815-561614788b41'
      },
      {
        name: 'French Fries',
        price: 79,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/frenchfries.jpeg',
        uuid: '2e94b59d-ee2e-4b02-9815-561614788b42'
      },
      {
        name: 'Peri Peri Fries',
        price: 79,
        description: 'Rich and aromatic caffeine shot',
        image: '/assets/img/menu/onWheels/Snacks/periperifries.jpeg',
        uuid: '2e94b59d-ee2e-4b02-9815-561614788b31'
      }
    ],    
  },
  
];
export { bakery, beverages, food ,onWheels};
